# CocoaPods
#   http://cocoapods.org
# Specs List- https://github.com/CocoaPods/Specs

# Supported Targets
platform :ios, '7.0'

# EstimoteSDK - iOS library for Estimote iBeacon devices
#  https://github.com/Estimote/iOS-SDK
pod 'EstimoteSDK', git: "https://github.com/Estimote/iOS-SDK.git", commit: "625440460b8d73adf321a1c9c4be9b6f19759bd9"

# AFNetworking - A delightful iOS and OS X networking framework
#  https://github.com/AFNetworking/AFNetworking
pod 'AFNetworking', '~> 2.3.1'
